name: Emulator Test
env:
  # The name of the main module repository
  main_project_module: app
on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]

jobs:
    android-tests:
        name: Tests on Android
        runs-on: macos-13
        timeout-minutes: 60
    
        strategy:
          fail-fast: false
          matrix:
            api-level: [ 33 ]
    
        steps:
    
          - name: Checkout Git repository
            uses: actions/checkout@v4
    
          - name: Restore local Maven repository
            uses: actions/cache@v4
            with:
              path: ~/.m2/repository
              key: tinylog3-android-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                tinylog3-android-${{ runner.os }}-maven-
    
          - name: Restore Gradle caches and wrapper
            uses: actions/cache@v4
            with:
              path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
              key: tinylog3-android-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
              restore-keys: |
                tinylog3-android-${{ runner.os }}-gradle-
    
          - name: Restore Android virtual device
            id: avd-cache
            uses: actions/cache@v4
            with:
              path: |
                ~/.android/avd/*
                ~/.android/adb*
              key: tinylog3-${{ runner.os }}-avd${{ matrix.api-level }}
    
          - name: Download and install JDK 17
            uses: actions/setup-java@v4
            with:
              distribution: zulu
              java-version: 17
    
          - name: Install core and impl artifacts via Maven
            run: mvn --batch-mode --update-snapshots --also-make --projects :tinylog-core,:tinylog-impl install -DskipTests
    
          - name: Set up Android virtual device if not cached
            uses: reactivecircus/android-emulator-runner@v2
            if: steps.avd-cache.outputs.cache-hit != 'true'
            with:
              api-level: ${{ matrix.api-level }}
              arch: x86_64
              target: ${{ matrix.api-level >= 30 && 'google_apis' || 'default' }}
              force-avd-creation: false
              emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
              disable-animations: false
              script: echo "Generated AVD snapshot for caching."
    
          - name: Run instrumented tests on Android virtual device
            uses: reactivecircus/android-emulator-runner@v2
            with:
              api-level: ${{ matrix.api-level }}
              arch: x86_64
              target: ${{ matrix.api-level >= 30 && 'google_apis' || 'default' }}
              force-avd-creation: false
              emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
              disable-animations: true
              script: chmod +x ./gradlew && ./gradlew createDebugCoverageReport spotbugsDebug checkstyle